version: '3.8'

services:
  mirador:
    build: .
    image: yourdockerhubusername/mirador:1.0
    ports:
      - "8082:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3