version: '3.8'

services:
  hugo-site:
    build: .
    image: yourdockerhubusername/hugo-site:1.0
    ports:
      - "1313:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
