version: '3.8'

services:
  react-hello:
    build: .
    image: yourdockerhubusername/react-hello:1.0-dev
    ports:
      - "3000:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

